name: bengkelku
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  firebase_auth: ^6.1.3
  shared_preferences: ^2.5.4
  cloud_firestore: ^6.1.1
  flutter_facebook_auth: ^7.1.2
  google_sign_in: ^7.2.0
  confetti: ^0.8.0
  image_picker: ^1.2.1
  google_maps_flutter: ^2.14.0
  geolocator: ^14.0.2
  permission_handler: ^12.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  image_path: assets/logo.png
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/
